trigger:
 branches:
   include:
     - main

pool: salim_pipeline3

stages:
  - stage:
    jobs:
      - job:
        steps:
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            backendServiceArm: 'salim_svc'
            backendAzureRmResourceGroupName: 'salim_rg1'
            backendAzureRmStorageAccountName: 'storagetestpipeline'
            backendAzureRmContainerName: 'storagecontainer'
            backendAzureRmKey: 'terraform.tfstate'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'validate'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'plan'
            environmentServiceNameAzureRM: 'salim_svc'